Create answer function
daisakuhazui/original_app pull request #10
Opened 2018-01-24 11:52 UTC by daisakuhazui

# WHAT
他ユーザーの質問に対する回答の表示と、回答を作成する機能を実装。
#WHY
フィードで表示させた質問に対して回答できるようにする。

2018-01-24 12:38 UTC, ArakawaShintaro requested changes

2018-01-24 12:38 UTC, ArakawaShintaro commented on app/models/answer.rb
> +    default_scope -> { order(created_at: :desc) }
よくわからないスペースが...

2018-01-24 12:38 UTC, ArakawaShintaro commented on app/controllers/answers_controller.rb
> +    @answer = current_user.answers.build(user_id: current_user.id, question_id: @question.id)
```
current_user.answers.build(question_id: @question.id)
```
これだけで、user_idがセットされているはずですがどうですかね

2018-01-24 12:38 UTC, ArakawaShintaro commented on app/views/answers/new.html.erb
> +@ <%= @question.user.alias_name %>
この@はなんですか？

2018-01-24 12:38 UTC, ArakawaShintaro commented on app/views/answers/new.html.erb
> +<%= render partial: 'shared/feed_answers', locals: { feed_answers_items: @feed_answers_items } %>
全体的によしなに空行がほしいですね。
グルーピングさせて、かたまりにした方がみやすいかと。

2018-01-24 12:38 UTC, ArakawaShintaro commented on app/views/questions/_question.html.erb
> +  <%= link_to "answer", controller: "answers", action: "new", id: question.id %>
スペース必要です

2018-01-24 23:34 UTC, daisakuhazui commented on app/controllers/answers_controller.rb
> +    @answer = current_user.answers.build(user_id: current_user.id, question_id: @question.id)
binding.pryで確認しました。
user_idガセットされていますね。ありがとうございます！

2018-01-24 23:35 UTC, daisakuhazui commented on app/models/answer.rb
> +    default_scope -> { order(created_at: :desc) }
直します…！

2018-01-24 23:36 UTC, daisakuhazui commented on app/views/answers/new.html.erb
> +@ <%= @question.user.alias_name %>
daisaku@DAISAKUのように、#{name}@#{alias_name}と表示させるための＠です。

2018-01-24 23:36 UTC, daisakuhazui commented on app/views/answers/new.html.erb
> +<%= render partial: 'shared/feed_answers', locals: { feed_answers_items: @feed_answers_items } %>
わかりました！

2018-01-24 23:38 UTC, daisakuhazui commented on app/views/questions/_question.html.erb
> +  <%= link_to "answer", controller: "answers", action: "new", id: question.id %>
インデントを調整します！

2018-01-25 01:04 UTC, ArakawaShintaro approved these changes
LGTM

2018-01-25 01:09 UTC, merged