【WIP】Add acts as follower
daisakuhazui/original_app pull request #6
Opened 2018-01-09 04:51 UTC by daisakuhazui

# WHAT
acts_as_followerというgemを用いてUserにフォロー機能を実装。

# WHY
質問（Questionモデル）を投稿するWebアプリを作成していいますが、UserモデルがQuestionモデルの親要素であるため。

2018-01-10 00:50 UTC, ArakawaShintaro requested changes

2018-01-10 00:50 UTC, ArakawaShintaro commented on app/views/shared/_stats.html.erb
> +<% @user ||= current_user %>
ここは変数にいれなくてもcurrent_userでいいんじゃないでしょうか

2018-01-10 00:50 UTC, ArakawaShintaro commented on app/views/users/_follow.html.erb
> +<%= form_for(current_user.followers.build(follower_id: @user.id)) do |f| %>
ここのエラーとしては下記が、空の配列になっているためbuildできないというようなエラーですよね
```
current_user.followers
```

2018-01-10 00:50 UTC, ArakawaShintaro commented on app/views/users/_follow_form.html.erb
> +<% unless current_user.id == @user %>
ここって、@user.idじゃないといけない気がします

2018-01-10 00:50 UTC, ArakawaShintaro commented on app/views/users/show.html.erb
> +<%= render 'users/follow_form' if user_signed_in? %>
render先で@userを使っていると思うのですが、ここで@userを渡さなくても変数はきちんと参照できていますか？

2018-01-13 15:43 UTC, ArakawaShintaro reviewed
ひとまず見ました！

2018-01-13 15:43 UTC, ArakawaShintaro commented on app/controllers/follows_controller.rb
> +    current_user.follow(@follow)
ここもし、ログインしていない人がfollowしたらどうなるんでしょうか？
current_userがとれなくてエラーがでてしまいますね。
ログインしてなければfollowボタンは非表示にする感じですかね？

2018-01-13 15:43 UTC, ArakawaShintaro commented on app/controllers/follows_controller.rb
> +    current_user.stop_following(@follow)
こちらも同上です

2018-01-13 15:43 UTC, ArakawaShintaro commented on app/controllers/follows_controller.rb
> +  def set_follow
いいっすね 👍

2018-01-13 15:43 UTC, ArakawaShintaro commented on app/controllers/users_controller.rb
> +    @user ||= current_user
ここって変数に入れる意味ってありますか！？

2018-01-13 15:43 UTC, ArakawaShintaro commented on config/routes.rb
> +  get "follows/create"
こちら、resourcesでfollow使ってるのに必要ですか？
また、create destoryそれぞれがgetってのもおかしいですね。
それぞれpost deleteにしないといけません。

2018-01-13 22:00 UTC, daisakuhazui commented on app/controllers/follows_controller.rb
> +    current_user.follow(@follow)
ログインしていない場合、followボタンは非表示にします。

2018-01-13 22:00 UTC, daisakuhazui commented on app/controllers/follows_controller.rb
> +    current_user.stop_following(@follow)
同上です。非表示にします。

2018-01-13 22:02 UTC, daisakuhazui commented on app/controllers/follows_controller.rb
> +  def set_follow
DRYを意識する余裕が出てきました✌️

2018-01-13 22:21 UTC, daisakuhazui commented on app/controllers/users_controller.rb
> +    @user ||= current_user
@userがnil、つまり自分のプロフィールを見た時にcurrent_userを自己代入すれば、フォロー数の表示がスムーズかなと思いました。（もちろん、実際はそんなことはないのですが）

でも今しがた試してみると、いちいち@userに代入しなくてもフォロー数取れていました・・・削除します。

2018-01-13 22:41 UTC, daisakuhazui commented on config/routes.rb
> +  get "follows/create"
おっしゃるように、不要です。
自動生成されたコードを放置しておりました。

2018-01-14 05:29 UTC, ArakawaShintaro reviewed
1点だけ気になりました！

2018-01-14 05:29 UTC, ArakawaShintaro commented on app/controllers/users_controller.rb
> +    else
elseの時は処理はどうしますか？

2018-01-14 05:36 UTC, daisakuhazui commented on app/controllers/users_controller.rb
> +    else
確認ありがとうございます。

elseの時はフォローボタンを表示しないので、特に処理は行いません。
・・・ということは、elseの記述がいらんということでしょうかね。試したところ、elseを削除しても問題なく動きましたので。

2018-01-14 11:30 UTC, ArakawaShintaro commented on app/controllers/users_controller.rb
> +
無駄な空行が...

2018-01-14 12:52 UTC, ArakawaShintaro approved these changes
こう言う細かいところは気をつけましょう(>_<)
おっけーです！

2018-01-14 12:59 UTC, daisakuhazui commented
@ArakawaShintaro 
了解です。確認ありがとうございます！

2018-01-15 12:34 UTC, ArakawaShintaro approved these changes
LGTM

2018-01-15 12:50 UTC, merged