add questions function
daisakuhazui/original_app pull request #7
Opened 2018-01-21 09:31 UTC by daisakuhazui

# WHAT
質問を投稿、自分のプロフィール画面で確認、削除する機能を実装しました。

# WHY
タイムライン形式での表示に向け、まずはUI上で質問を操作できるようにする必要があります。

2018-01-21 09:36 UTC, ArakawaShintaro commented on app/controllers/questions_controller.rb
> +    @question.destroy
削除される時に、current_userかどうか判断した方がいいともいますよ！

2018-01-21 09:52 UTC, daisakuhazui commented on app/controllers/questions_controller.rb
> +    @question.destroy
```
before_action :correct_user, only: :destroy
・
・
・
private
・
  def correct_user
    @question = current_user.questions.find_by(id: params[:id])
    redirect_to root_url if @question.nil?
  end
end
```
ありがとうございます！
currento_user かどうかの判断とは、上記に加えてっていうことでしょうか？？

2018-01-21 10:24 UTC, ArakawaShintaro commented on app/controllers/questions_controller.rb
> +    @question.destroy
before_actionでしなくても
```
if current_user
   @question = current_user.questions.find_by(id: params[:id])
   @question.destory
else
 ~~~
end
```
とかの方がいいと思います。

before_actionはDRYにしたいときに使用するのがベターかなと！

2018-01-21 10:26 UTC, daisakuhazui commented on app/controllers/questions_controller.rb
> +    @question.destroy
なるほど、わかりました！

2018-01-21 11:54 UTC, ArakawaShintaro requested changes

2018-01-21 11:54 UTC, ArakawaShintaro commented on app/controllers/questions_controller.rb
> +    @question = current_user.questions.find_by(id: params[:id])
まずさっきみたいにif文でやったほうがいいのと、
3行目のbefore_actionの削除も忘れていますね。

2018-01-21 13:28 UTC, ArakawaShintaro approved these changes
LGTM

2018-01-21 21:44 UTC, merged

2018-01-22 03:42 UTC, ArakawaShintaro reviewed
LGTMだしちゃったので、他のPRで修正しておいてください

2018-01-22 03:42 UTC, ArakawaShintaro commented on app/views/questions/index.html.erb
> +  <%= render partial: 'shared/question_form', locals: {question: @question} %>
```
{ ハッシュは左右半角スペース }
```

2018-01-22 03:42 UTC, ArakawaShintaro commented on app/views/questions/_question.html.erb
> +  <%= link_to "delete", question_path(question), method: :delete, data:{confirm: "You sure?"} %>
```
{ ハッシュは左右半角スペース }
```

2018-01-22 03:44 UTC, daisakuhazui commented on app/views/questions/index.html.erb
> +  <%= render partial: 'shared/question_form', locals: {question: @question} %>
確認ありがとうございます！修正します。